sudo: false
dist: trusty
language: go
go:
  - "1.13"
before_script:
  - wget https://github.com/goreleaser/goreleaser/releases/download/v0.123.3/goreleaser_Linux_x86_64.tar.gz -O /tmp/goreleaser.tar.gz
  - tar -xvf /tmp/goreleaser.tar.gz -C /tmp/
  - sudo mv /tmp/goreleaser /usr/local/bin/
script:
  - make tools
  - make
after_success:
  - if [[ -n "$TRAVIS_TAG" ]]; then make release; fi
notifications:
  email: true
